const keyBoardMatrix = [
  ['Backquote', 'Digit1', 'Digit2', 'Digit3', 'Digit4', 'Digit5', 'Digit6', 'Digit7', 'Digit8', 'Digit9', 'Digit0', 'Minus', 'Equal', 'Backspace'],
  ['Tab', 'KeyQ', 'KeyW', 'KeyE', 'KeyR', 'KeyT', 'KeyY', 'KeyU', 'KeyI', 'KeyO', 'KeyP', 'BracketLeft', 'BracketRight', 'Backslash'],
  ['CapsLock', 'KeyA', 'KeyS', 'KeyD', 'KeyF', 'KeyG', 'KeyH', 'KeyJ', 'KeyK', 'KeyL', 'Semicolon', 'Quote', 'Enter'],
  ['ShiftLeft', 'KeyZ', 'KeyX', 'KeyC', 'KeyV', 'KeyB', 'KeyN', 'KeyM', 'Comma', 'Period', 'Slash', 'ArrowUp', 'ShiftRight'],
  ['ControlLeft', 'MetaLeft', 'AltLeft', 'Space', 'AltRight', 'ControlRight', 'ArrowLeft', 'ArrowDown', 'ArrowRight'],
];

const keyboardProperties = {
  AltLeft: {
    title: 'Alt', size: 'Double', action: 'changeLanguage', condition: 'ControlLeft|ControlRight',
  },
  AltRight: { title: 'Alt', action: 'changeLanguage', condition: 'ControlLeft|ControlRight' },
  ArrowDown: { title: '&#8595;' },
  ArrowLeft: { title: '&#8592;' },
  ArrowRight: { title: '&#8594;' },
  ArrowUp: { title: '&#8593;' },
  Backquote: { default: '`', shift: '~', ru: 'Ё' },
  Backslash: { default: '\\', shift: '|', ru_shift: '/' },
  Backspace: { title: 'Backspace', size: 'Double' },
  BracketLeft: { default: '[', shift: '{', ru: 'Х' },
  BracketRight: { default: ']', shift: '}', ru: 'Ъ' },
  CapsLock: { title: 'CapsLock', size: 'Double' },
  Comma: { default: ',', shift: '&lt;', ru: 'Б' },
  ControlLeft: {
    title: 'Ctrl', size: 'Double', action: 'changeLanguage', condition: 'AltLeft|AltRight',
  },
  ControlRight: { title: 'Ctrl', action: 'changeLanguage', condition: 'AltLeft|AltRight' },
  Digit0: { default: '0', shift: ')' },
  Digit1: { default: '1', shift: '!' },
  Digit2: { default: '2', shift: '@', ru_sfift: '"' },
  Digit3: { default: '3', shift: '#', ru_sfift: '№' },
  Digit4: { default: '4', shift: '$', ru_sfift: ';' },
  Digit5: { default: '5', shift: '%' },
  Digit6: { default: '6', shift: '^', ru_sfift: ':' },
  Digit7: { default: '7', shift: '&', ru_sfift: '?' },
  Digit8: { default: '8', shift: '*' },
  Digit9: { default: '9', shift: ')' },
  Enter: { title: 'Enter', size: 'Double' },
  Equal: { default: '=', shift: '+' },
  KeyA: { default: 'A', ru: 'Ф', gr: 'Α' },
  KeyB: { default: 'B', ru: 'И', gr: 'Β' },
  KeyC: { default: 'C', ru: 'С', gr: 'Ψ' },
  KeyD: { default: 'D', ru: 'В', gr: 'Δ' },
  KeyE: { default: 'E', ru: 'У', gr: 'Ε' },
  KeyF: { default: 'F', ru: 'А', gr: 'Φ' },
  KeyG: { default: 'G', ru: 'П', gr: 'Γ' },
  KeyH: { default: 'H', ru: 'Р', gr: 'Η' },
  KeyI: { default: 'I', ru: 'Ш', gr: 'Ι' },
  KeyJ: { default: 'J', ru: 'О', gr: 'Ξ' },
  KeyK: { default: 'K', ru: 'Л', gr: 'Κ' },
  KeyL: { default: 'L', ru: 'Д', gr: 'Λ' },
  KeyM: { default: 'M', ru: 'Ь', gr: 'Μ' },
  KeyN: { default: 'N', ru: 'Т', gr: 'Ν' },
  KeyO: { default: 'O', ru: 'Щ', gr: 'Ο' },
  KeyP: { default: 'P', ru: 'З', gr: 'Π' },
  KeyQ: { default: 'Q', ru: 'Й', gr: ':' },
  KeyR: { default: 'R', ru: 'К', gr: 'Ρ' },
  KeyS: { default: 'S', ru: 'Ы', gr: 'σ' },
  KeyT: { default: 'T', ru: 'Е', gr: 'Τ' },
  KeyU: { default: 'U', ru: 'Г', gr: 'Θ' },
  KeyV: { default: 'V', ru: 'М', gr: 'Ω' },
  KeyW: { default: 'W', ru: 'Ц', gr: 'ς' },
  KeyX: { default: 'X', ru: 'Ч', gr: 'Χ' },
  KeyY: { default: 'Y', ru: 'Н', gr: 'Υ' },
  KeyZ: { default: 'Z', ru: 'Я', gr: 'Ζ' },
  Minus: { default: '-', shift: '_' },
  MetaLeft: { title: 'Win' },
  Period: { default: '.', shift: '>', ru: 'Ю' },
  Quote: { default: "'", shift: '"', ru: 'Э' },
  Semicolon: { default: ';', shift: ':', ru: 'Ж' },
  ShiftLeft: { title: 'Shift', size: 'Double' },
  ShiftRight: { title: 'Shift', size: 'Double' },
  Slash: {
    default: '/', shift: '?', ru: '.', ru_sfift: ',',
  },
  Space: { title: 'Space', default: ' ', size: 'SpaceButton' },
  Tab: { title: 'Tab', size: 'Double' },
};

export { keyBoardMatrix, keyboardProperties };
