const KEYS_DATA = {
  AltLeft: {
    title: 'Alt',
    styles: 'Double',
    action: 'changeLanguage',
    conditions: ['ControlLeft', 'ControlRight'],
  },
  AltRight: {
    title: 'Alt',
    action: 'changeLanguage',
    conditions: ['ControlLeft', 'ControlRight'],
  },
  ArrowDown: { default: '↓' },
  ArrowLeft: { default: '←' },
  ArrowRight: { default: '→' },
  ArrowUp: { default: '↑' },
  Backquote: {
    default: '`',
    shift: '~',
    ru: 'Ё',
    ru_shift: 'Ё',
  },
  Backslash: { default: '\\', shift: '|', ru_shift: '/' },
  Backspace: { title: 'Backspace', styles: 'Double', action: 'Backspace' },
  BracketLeft: {
    default: '[', shift: '{', ru: 'Х', ru_shift: 'Х',
  },
  BracketRight: {
    default: ']', shift: '}', ru: 'Ъ', ru_shift: 'Ъ',
  },
  CapsLock: { title: 'CapsLock', styles: 'Double', action: 'CapsLock' },
  Comma: {
    default: ',', shift: '&lt;', ru: 'Б', ru_shift: 'Б',
  },
  ControlLeft: {
    title: 'Ctrl',
    styles: 'Double',
    action: 'changeLanguage',
    conditions: ['AltLeft', 'AltRight'],
  },
  ControlRight: {
    title: 'Ctrl',
    action: 'changeLanguage',
    conditions: ['AltLeft', 'AltRight'],
  },
  Digit0: { default: '0', shift: ')' },
  Digit1: { default: '1', shift: '!' },
  Digit2: { default: '2', shift: '@', ru_shift: '"' },
  Digit3: { default: '3', shift: '#', ru_shift: '№' },
  Digit4: { default: '4', shift: '$', ru_shift: ';' },
  Digit5: { default: '5', shift: '%' },
  Digit6: { default: '6', shift: '^', ru_shift: ':' },
  Digit7: { default: '7', shift: '&', ru_shift: '?' },
  Digit8: { default: '8', shift: '*' },
  Digit9: { default: '9', shift: ')' },
  Enter: { title: 'Enter', styles: 'Double', action: 'Enter' },
  Equal: { default: '=', shift: '+' },
  KeyA: { default: 'A', ru: 'Ф' },
  KeyB: { default: 'B', ru: 'И' },
  KeyC: { default: 'C', ru: 'С' },
  KeyD: { default: 'D', ru: 'В' },
  KeyE: { default: 'E', ru: 'У' },
  KeyF: { default: 'F', ru: 'А' },
  KeyG: { default: 'G', ru: 'П' },
  KeyH: { default: 'H', ru: 'Р' },
  KeyI: { default: 'I', ru: 'Ш' },
  KeyJ: { default: 'J', ru: 'О' },
  KeyK: { default: 'K', ru: 'Л' },
  KeyL: { default: 'L', ru: 'Д' },
  KeyM: { default: 'M', ru: 'Ь' },
  KeyN: { default: 'N', ru: 'Т' },
  KeyO: { default: 'O', ru: 'Щ' },
  KeyP: { default: 'P', ru: 'З' },
  KeyQ: { default: 'Q', ru: 'Й' },
  KeyR: { default: 'R', ru: 'К' },
  KeyS: { default: 'S', ru: 'Ы' },
  KeyT: { default: 'T', ru: 'Е' },
  KeyU: { default: 'U', ru: 'Г' },
  KeyV: { default: 'V', ru: 'М' },
  KeyW: { default: 'W', ru: 'Ц' },
  KeyX: { default: 'X', ru: 'Ч' },
  KeyY: { default: 'Y', ru: 'Н' },
  KeyZ: { default: 'Z', ru: 'Я' },
  Minus: { default: '-', shift: '_' },
  MetaLeft: { title: 'Win' },
  Period: {
    default: '.', shift: '>', ru: 'Ю', ru_shift: 'Ю',
  },
  Quote: {
    default: "'", shift: '"', ru: 'Э', ru_shift: 'Э',
  },
  Semicolon: {
    default: ';', shift: ':', ru: 'Ж', ru_shift: 'Ж',
  },
  ShiftLeft: { title: 'Shift', styles: 'Double', action: 'Shift' },
  ShiftRight: { title: 'Shift', action: 'Shift' },
  Slash: {
    default: '/', shift: '?', ru: '.', ru_shift: ',', styles: 'Double',
  },
  Space: { title: 'Space', default: ' ', styles: 'SpaceButton' },
  Tab: { title: 'Tab', styles: 'Double', action: 'Tab' },
};

export default KEYS_DATA;
